package edu.utn.TpFinal.Exceptions;

public class CallAlreadyExists extends Exception{
}
